language: ruby
branches:
  only:
    - develop
    - master
rvm:
  - 1.8.7
  - 1.9.3
before_install:
  - gem update --system 1.8.5
  - gem update --system 1.6.2
  - gem install rake --version=0.9.2.2
  - git submodule update --init --recursive
  - psql -c "create database foi_test template template0 encoding 'SQL_ASCII';" -U postgres
  - cp config/database.yml-test config/database.yml
  - cp config/general.yml-example config/general.yml
  - cp config/newrelic.yml-example config/newrelic.yml
  - sudo apt-get update
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -y install exim4-daemon-light
  - sudo apt-get -y install `cut -d " " -f 1 config/packages | egrep -v "(^#|wkhtml|bundler|^ruby$|^ruby1.8$|^rubygems$|^rake)"`
  - RAILS_ENV=test ./script/rails-post-deploy
before_script:
notifications:
  irc: "irc.freenode.org#alaveteli"
  email:
    recipients:
      - cron-whatdotheyknow@mysociety.org
