safe: true
highlighter: rouge
baseurl: ""
permalink: pretty
markdown: kramdown
url: http://code.alaveteli.org
defaults:
  -
    scope:
      path: es
    values:
      baseurl: /es
exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - alaveteli-doc-master.txt
  - node_modules
  - package.json
  - bin
  - cache
  - commonlib
  - config
  - coverage
  - db
  - files
  - jekyll
  - lib
  - log
  - public
  - script
  - tmp
  - vendor
plugins:
  - jekyll-redirect-from
jurisdictions: "25"
requests: "800,000"
languages: "20"
