safe: true
highlighter: rouge
baseurl: /
permalink: pretty
markdown: kramdown
url: http://code.alaveteli.org
defaults:
  -
    scope:
      path: .
    values:
      baseurl: /
  -
    scope:
      path: es
    values:
      baseurl: /es
exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - alaveteli-doc-master.txt
  - node_modules
  - package.json
  - script
  - vendor
gems:
  - jekyll-redirect-from
jurisdictions: "25"
requests: "315,000"
languages: "20"
