- title: WhatDoTheyKnow
  url: https://www.whatdotheyknow.com
  image: what-do-they-know.jpg
  featured: true
  pro: true
  country:
    en: United Kingdom
    es: Reino Unido
  description:
    en: |
      <p>Alaveteli started life as <a href="https://www.whatdotheyknow.com">WhatDoTheyKnow</a>, a website produced by <a href="https://mysociety.org/">mySociety</a> for making FOI requests in the UK.</p>
      <p>Around 15% to 20% of requests to UK Central Government are made through WhatDoTheyKnow.com.</p>
    es: |
      <p>Alaveteli cobró vida con <a href="https://www.whatdotheyknow.com">WhatDoTheyKnow</a>, un sitio web producido por <a href="https://mysociety.org/">mySociety</a> para realizar solicitudes de información pública en el Reino Unido.</p>
      <p>A través de WhatDoTheyKnow.com se llevan a cabo entre un 15% y un 20% de las solicitudes recibidas por el gobierno central de Reino Unido.</p>

- title: Ask the EU
  url: https://www.asktheeu.org
  image: ask-the-eu.jpg
  featured: true
  pro: true
  country:
    en: Europe
    es: Europa
  description:
    en: |
      <p>AskTheEU doesn’t just cover one country: in theory, it serves over 500 million people: the whole of Europe.</p>
      <p>AskTheEU processes requests for any of the European Union bodies, and the site is translated into several languages. It is run by <a href="https://www.access-info.org/">Access Info Europe</a>, in Madrid.</p>
    es: |
      <p>AskTheEU no da soporte a un solo país, sino que ofrece sus servicios a más de 500 millones de personas: a toda Europa.</p>
      <p>AskTheEU procesa solicitudes para todos los organismos que forman parte de la Unión Europea y está traducido a diversos idiomas. <a href="https://www.access-info.org/">Access Info Europe</a> (Madrid) se encarga de su gestión.</p>

- title: Info Pro Všechny
  url: https://www.infoprovsechny.cz
  image: informace-pro-vsechny.jpg
  featured: true
  pro: true
  country:
    en: Czech Republic
    es: República Checa
  description:
    en: |
      <p>Infoprovsechny gives citizens of the Czech Republic easy access to their rights under the country's 1999 Freedom of Information Act.</p>
      <p>Giving access to nearly 12,000 public authorities, the site has been instrumental in several high-profile TV news stories. It was started in 2012 with a grant from the Open Society Foundation.</p>
    es: |
      <p>Infoprovsechny gives citizens of the Czech Republic easy access to their rights under the country's 1999 Freedom of Information Act.</p>
      <p>Giving access to nearly 12,000 public authorities, the site has been instrumental in several high-profile TV news stories. It was started in 2012 with a grant from the Open Society Foundation.</p>

- title: MaDada
  url: https://madada.fr
  image: ma-dada.jpg
  featured: true
  pro: true
  country:
    en: France
    es: Francia
  description:
    en: |
      <p>France has had access to information since 1978, thanks to their Freedom of Information Act — but it wasn't until the launch of MaDada in 2020 that citizens were given a simple way to exercise this right.</p>
      <p>The site is run by a group of dedicated volunteers, as well as members of OpenKnowledge France.</p>
    es: |
      <p>France has had access to information since 1978, thanks to their Freedom of Information Act — but it wasn't until the launch of MaDada in 2020 that citizens were given a simple way to exercise this right.</p>
      <p>The site is run by a group of dedicated volunteers, as well as members of OpenKnowledge France.</p>

- title: Handlingar
  url: https://handlingar.se
  image: handlingar.jpg
  featured: true
  pro: true
  country:
    en: Sweden
    es: Suecia
  description:
    en: |
      <p>Sweden is the country where <i>offentlighetsprincipen</i>, the Principle of Public Access — the first FOI legislation as we know it today — was born.</p>
      <p>More than 250 years later, a group of volunteers are continuing to push the boundaries to information access, with Handlingar.</p>
    es: |
      <p>Sweden is the country where <i>offentlighetsprincipen</i>, the Principle of Public Access — the first FOI legislation as we know it today — was born.</p>
      <p>More than 250 years later, a group of volunteers are continuing to push the boundaries to information access, with Handlingar.</p>

- title: de Wob-Knop
  url: https://www.wob-knop.nl
  image: de-wob-knop.jpg
  featured: true
  pro: true
  country:
    en: Netherlands
    es: Países Bajos
  description:
    en: |
      <p>It took just one enterprising journalist to set up and run de Wob-Knop  — with valuable support from <a href="https://www.vvoj.org/">Vereniging van Onderzoeksjournalisten</a>.</p>
      <p>The underlying aim is to encourage more online FOI requesting in the Netherlands, using a request generator which will eventually link into the platform.</p>
    es: |
      <p>It took just one enterprising journalist to set up and run de Wob-Knop  — with valuable support from <a href="https://www.vvoj.org/">Vereniging van Onderzoeksjournalisten</a>.</p>
      <p>The underlying aim is to encourage more online FOI requesting in the Netherlands, using a request generator which will eventually link into the platform.</p>

- title: Transparencia
  url: https://transparencia.be
  image: transparencia-be.jpg
  featured: false
  pro: true
  country:
    en: Belgium
    es: Bélgica

- title: Imamo pravo znati
  url: https://imamopravoznati.org
  image: imamo-pravo-znati.jpg
  featured: false
  pro: false
  country:
    en: Croatia
    es: Croacia

- title: Ki Mit Tud
  url: https://kimittud.atlatszo.hu
  image: ki-mit-tud.jpg
  featured: false
  pro: false
  country:
    en: Hungary
    es: Hungría

- title: Доступ до правди
  url: https://dostup.pravda.com.ua
  image: ukraine.jpg
  featured: false
  pro: false
  country:
    en: Ukraine
    es: Ucrania

- title: Mimes Brønn
  url: https://www.mimesbronn.no
  image: mimes-bronn.jpg
  featured: false
  pro: false
  country:
    en: Norway
    es: Noruega

- title: Bilmehakki
  url: http://bilmehakki.org
  image: bilmehakki.jpg
  featured: false
  pro: false
  country:
    en: Turkey
    es: Turquía

- title: Ask Data
  url: http://askdata.org.il
  image: ask-data.jpg
  featured: false
  pro: false
  country:
    en: Israel
    es: Israel

- title: Informini
  url: https://www.informini.org
  image: informini.jpg
  featured: false
  pro: false
  country:
    en: Tunisia
    es: Túnez

- title: Sobanukirwa
  url: https://sobanukirwa.rw
  image: sobanukirwa.jpg
  featured: false
  pro: false
  country:
    en: Rwanda
    es: Ruanda

- title: accessinfo.hk
  url: https://accessinfo.hk
  image: access-info-hk.jpg
  featured: false
  pro: false
  country:
    en: Hong Kong
    es: Hong Kong

- title: Ask Your Gov
  url: https://askyourgov.ug
  image: ask-your-gov-uganda.jpg
  featured: false
  pro: false
  country:
    en: Uganda
    es: Uganda

- title: Right To Know
  url: https://www.righttoknow.org.au
  image: right-to-know.jpg
  featured: false
  pro: true
  country:
    en: Australia
    es: Australia

- title: FYI
  url: https://fyi.org.nz
  image: fyi.jpg
  featured: false
  pro: false
  country:
    en: New Zealand
    es: Nueva Zelanda

- title: Qué Sabés
  url: https://quesabes.org
  image: que-sabes.jpg
  featured: false
  pro: false
  country:
    en: Uruguay
    es: Uruguay

- title: Derecho A Preguntar
  url: https://derechoapreguntar.org
  image: derecho-a-preguntar.jpg
  featured: false
  pro: false
  country:
    en: Nicaragua
    es: Nicaragua

- title: InfoLib
  url: http://infolib.org.lr
  image: infolib.jpg
  featured: false
  pro: false
  country:
    en: Liberia
    es: Liberia

- title: Queremosdatos
  url: https://www.queremosdatos.co
  image: queremos-datos.jpg
  featured: false
  pro: false
  country:
    en: Colombia
    es: Colombia

- title: OPRA Machine
  url: https://opramachine.com
  image: opra-machine.jpg
  featured: false
  pro: false
  country:
    en: New Jersey, USA
    es: New Jersey, Estados Unidos

- title: Derecho al Dato
  url: https://derechoaldato.com.ar
  image: derecho-al-dato.jpg
  featured: false
  pro: false
  country:
    en: Argentina
    es: Argentina
